name: CI-Rolling

on:
  workflow_dispatch:
  push:
    branches:
      - ros2
  pull_request:
    branches:
      - ros2

jobs:
  harmonic_ci:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ROS_REPO: [testing, main]
    steps:
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          use-ros2-testing: ${{ matrix.ROS_REPO == 'testing' }}
      - name: Run ROS CI
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: rolling
          import-token: ${{ secrets.GITHUB_TOKEN }}
