name: CI-Rolling

on:
  workflow_dispatch:
  push:
    branches:
      - ros2
  pull_request:
    branches:
      - ros2

jobs:
  ionic_ci:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:noble
    strategy:
      fail-fast: false
      matrix:
        ROS_REPO: [testing, main]
    steps:
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          use-ros2-testing: ${{ matrix.ROS_REPO == 'testing' }}
      - name: Run ROS CI
        uses: ros-tooling/action-ros-ci@0.3.8
        with:
          target-ros2-distro: rolling
          import-token: ${{ secrets.GITHUB_TOKEN }}
